# Generated by Django 3.2.5 on 2022-01-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['Id']},
        ),
    ]
